# Generated by Django 5.2.2 on 2025-07-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="admin_reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
