# Generated by Django 5.2.2 on 2025-07-15 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_contact_admin_reply_contact_replied_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_image", models.ImageField(upload_to="ecg_images/")),
                ("predicted_label", models.CharField(max_length=255)),
                (
                    "prediction_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-prediction_date"],
            },
        ),
        migrations.DeleteModel(
            name="Users",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="secret_answer",
            new_name="secret_answer_hash",
        ),
    ]
